apiVersion: v2v.kubevirt.io/v1alpha1
kind: VirtualMachineImport
metadata:
  name: example-vmware-virtualmachineimport
  namespace: example-ns
  annotations:
    vmimport.v2v.kubevirt.io/progress: "20"
    vmimport.v2v.kubevirt.io/propagate-annotations: "{'description': 'My description.'}"
  labels:
    vmimport.v2v.kubevirt.io/tracker: "vmimport-123"
spec:
  providerCredentialsSecret: # A secret holding vCenter credentials
    name: my-secret-with-vmware-credentials
    namespace: default # optional, if not specified, use CR's namespace
  resourceMapping:
    name: vmware-to-kubevirt # a mapping of vmware resources to kubevirt resources
    namespace: othernamespace # optional, if not specified, use CR's namespace
  targetVmName: examplevm # The target name is optional. If not provided, the import will attempt to use the origin name of the VM or to normalize it.
  startVm: true # should the vm be started after the vm was created on kubevirt
  source:
    vmware: # import from a vmware source
      vm: # The VM's managed object reference in vCenter is used to uniquely identify it.
        id: vm-1234
      mappings:
        networkMapping:
          - source:
              name: network-1
            target:
              name: pod
            type: pod
        diskMappings: # specifies per-disk placement on storage class
          - source:
              id: 8181ecc1-5db8-4193-9c92-3ddab3be7b05
            target:
              name: storage_class_1
status:
  targetVmName: myvm # the name of the created virtual machine
  conditions:
    - type: Succeeded # indicates if the VM import process succeeded or failed
      status: "False"
      reason: ValidationFailed
      message: Failed to validate mapping rules for the VM.
      lastTransitionTime: "2020-02-20T12:43:10Z"
    - status: "True"
      type: Processing # indicates if the VM import process is running
      reason: CopyingDisks
      message: VM disks are being copied to the destination.
      lastTransitionTime: "2020-02-20T12:43:10Z"
  dataVolumes: # list of data volumes created for the VMs
    - name: dv-examplevm-1
    - name: dv-examplevm-2
