---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-with-vmware-credentials
type: Opaque
stringData:
  vmware: |
    apiUrl: "https://my.vcenter.example.com/sdk"
    username: administrator@vsphere.local # provided in the format of username@domain
    password: 123456
    insecure: false


